# Generated by Django 6.0.5 on 2026-05-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='recurso',
        ),
        migrations.AddField(
            model_name='reserva',
            name='recursos',
            field=models.ManyToManyField(related_name='reservas', to='reservas.recurso'),
        ),
    ]
